stages:
  - analyze
  - test
  - codecov

variables:
  FRAMEWORK_NAME: "LocalizeChecker"

# A job for analyzing code via Swiftlint
Lint:
  stage: analyze
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: '$CI_COMMIT_TAG'
      when: always
  script:
    - swiftlint

# A job for running unit tests on MRs and before a release
Test:
  stage: test
  rules:
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH =~ /^test.*$/
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: "$CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH =~ /^master|main*$/"
      changes:
        - Sources/**/*
        - Tests/**/*
      when: always
    - if: '$TEST'
      when: always
  script:
    - swift test --enable-code-coverage
  artifacts:
   paths:
    - .build/debug/${FRAMEWORK_NAME}PackageTests.xctest/
    - .build/debug/codecov/

Cove coverage:
  stage: codecov
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH =~ /^master|main*$/"
      changes:
        - Sources/**/*
        - Tests/**/*
      when: always
    - if: '$CODECOV'
      when: always
  before_script:
    - pip install lcov_cobertura
    - brew install xmlstarlet
  script:
    - sh .ci/coverage.sh
  needs: ["Test"]
  coverage: '/^gitlab-coverage .+%$/'
  artifacts:
    reports:
      cobertura: coverage.xml