stages:
  - analyze
  - test

# A job for analyzing code via Swiftlint
Lint:
  stage: analyze
  tags:
    - utils
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: '$CI_COMMIT_TAG'
      when: always
  script:
    - swiftlint

# A job for running unit tests on MRs and before a release
Test:
  stage: test
  rules:
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH =~ /^test.*$/
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: '$TEST'
      when: always
  script:
    - swift test
