name: Swift Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: swift test --explicit-target-dependency-import-check error